# Completing the list of words with at least 4 letters correctly
word_list = [
    "apple", "beautiful", "potato", "orange", "banana", "grape", "cherry",
    "mango", "peach", "kiwi", "lemon", "melon", "berry", "plum", "apricot",
    "coconut", "papaya", "cucumber", "tomato", "carrot", "onion", "lettuce",
    "spinach", "broccoli", "pumpkin", "squash", "zucchini", "radish",
    "asparagus", "artichoke", "celery", "eggplant", "bean", "corn", "peas",
    "chickpea", "quinoa", "tofu", "rice", "barley", "wheat", "oat",
    "pasta", "bread", "cake", "cookie", "pie", "brownie", "pudding",
    "soup", "cereal", "salad", "salsa", "syrup", "jam", "jelly", "pickles",
    "honey", "chocolate", "vanilla", "caramel", "cinnamon", "ginger",
    "pepper", "nutmeg", "clove", "basil", "oregano", "thyme", "rosemary",
    "sage", "parsley", "chili", "jalapeno", "wasabi", "avocado", "almond",
    "cashew", "walnut", "hazelnut", "peanut", "pecan", "pistachio",
    "sunflower", "pumpkin", "flaxseed", "chia", "sesame", "tahini",
    "olive", "coconut", "oil", "vinegar", "mustard", "ketchup", "mayo",
    "sauce", "dressing", "spice", "seasoning", "marinade", "broth",
    "gravy", "stew", "curry", "fajita", "taco", "burrito", "quesadilla",
    "samosa", "dumpling", "springroll", "sushi", "tempura", "noodle",
    "couscous", "pasta", "lasagna", "ravioli", "gnocchi", "tortellini",
    "pizza", "scone", "croissant", "baguette", "roll", "doughnut",
    "muffin", "biscuit", "waffle", "crepe", "pancake", "tart", "strudel",
    "fritter", "gelato", "icecream", "sorbet", "yogurt", "milkshake",
    "smoothie", "cocktail", "margarita", "mojito", "sangria", "punch",
    "pina", "colada", "juice", "tea", "coffee", "latte", "espresso",
    "chai", "cocoa", "soda", "lemonade", "water", "milk", "buttermilk",
    "nutmilk", "soy", "almond", "coconut", "rice", "skim", "whole",
    "lowfat", "cream", "half", "butter", "cheese", "yogurt", "sour",
    "gouda", "cheddar", "feta", "brie", "parmesan", "mozzarella",
    "ricotta", "creamcheese", "blue", "vegan", "marble", "string",
    "provolone", "camembert", "colby", "swiss", "asiago", "chevre",
    "fontina", "halloumi", "queso", "paneer", "taco", "enchilada",
    "wrap", "cabbage", "sauerkraut", "pickles", "salsa", "ketchup",
    "mustard", "mayo", "barbecue", "relish", "hot", "sauce", "soy",
    "sriracha", "teriyaki", "balsamic", "apple", "cider", "vinaigrette",
    "hummus", "salsa", "sauce", "puree", "dip", "spread", "paste",
    "tahini", "guacamole", "pesto", "salsa", "sauce", "relish", "ratatouille",
    "baba", "ganoush", "tapenade", "pesto", "baguette", "roll", "ciabatta",
    "focaccia", "pita", "naan", "tortilla", "crust", "crackers", "toast",
    "crouton", "puff", "pastry", "wonton", "dim", "sum", "samosa",
    "eggroll", "cannoli", "baklava", "tiramisu", "mousse", "tart",
    "flan", "panna", "cotta", "meringue", "millefeuille", "cupcake",
    "brownie", "blondie", "cheesecake", "creme", "brulee", "parfait",
    "profiterole", "caramel", "fondant", "sorbet", "gelato", "ice",
    "cream", "frozen", "yogurt", "smoothie", "milkshake", "float",
    "sundae", "popsicle", "fudge", "truffle", "brittle", "rock",
    "candy", "sugar", "toffee", "caramel", "peanut", "brittle", "marshmallow",
    "jelly", "licorice", "chocolate", "peppermint", "gumdrop", "hard",
    "candy", "gummy", "candy", "taffy", "bonbon", "chocolate", "bark",
    "truffle", "fudge", "nougat", "cotton", "candy", "chewy", "treat",
    "sucker", "jawbreaker", "rock", "candy", "candy", "corn", "chocolate",
    "strawberry", "watermelon", "banana", "lime", "grapefruit", "lemon",
    "orange", "kiwi", "papaya", "peach", "pineapple", "coconut", "plum",
    "fig", "date", "berry", "cherry", "grape", "tangerine", "pomegranate",
    "clementine", "nectarine", "dragonfruit", "rhubarb", "jackfruit",
    "persimmon", "passionfruit", "starfruit", "apricot", "soursop",
    "custardapple", "longan", "lychee", "pawpaw", "mulberry", "raspberry",
    "blueberry", "blackberry", "currant", "gooseberry", "huckleberry",
    "boysenberry", "cranberry", "barberry", "elderberry", "coconut",
    "cacao", "caffeine", "lemonade", "punch", "pisco", "whiskey",
    "vodka", "gin", "rum", "tequila", "schnapps", "absinthe", "brandy",
    "liqueur", "aperitif", "digestif", "spirit", "prosecco", "champagne",
    "merlot", "cabernet", "sauvignon", "pinot", "noir", "shiraz", "malbec",
    "chianti", "zinfandel", "chardonnay", "sauvignon", "blanc", "moscato",
    "riesling", "vin", "rose", "sparkling", "white", "red", "wine",
    "beer", "lager", "ale", "stout", "porter", "pilsner", "lager",
    "ipa", "saison", "wheat", "bock", "barley", "hops", "yeast",
    "ferment", "brewing", "distilling", "vineyard", "brewery", "winery",
    "winemaking", "cider", "mead", "spirits", "cocktail", "mixer",
    "garnish", "tumbler", "shaker", "shot", "jigger", "bitters",
    "syrup", "vermouth", "liqueur", "soda", "tonic", "sparkling",
    "water", "ice", "garnish", "fruit", "glass", "stir", "shake",
    "pour", "serve", "mix", "blend", "infuse", "muddle", "strain",
    "chill", "garnish", "twist", "slice", "peel", "zest", "blend",
    "stir", "whip", "beat", "fold", "drizzle", "sauté", "braise",
    "roast", "grill", "broil", "fry", "steam", "boil", "bake",
    "simmer", "poach",
]